Removed magic numbers
peiva-git/SDM_project pull request #135
Opened 2023-06-07 13:58 UTC by peiva-git

While removing some magic numbers, I noticed that the allowed `Position` coordinates should also have some limitations due to how the `Position` class is implemented. I added some tests to reflect the desired behavior and corrected the constructor code accordingly.

2023-06-09 19:24 UTC, manuelkoso requested changes
There are missing some visibility keywords.

2023-06-09 19:24 UTC, manuelkoso commented on core/src/it/units/sdm/project/board/Position.java
> +    static final int MAXIMUM_COLUMN_INDEX = 25;
Missing visibility keyword

2023-06-09 19:24 UTC, manuelkoso commented on core/src/it/units/sdm/project/game/gui/screens/GameScreen.java
> +    static final int GAME_SCREEN_WORLD_WIDTH = TILE_SIZE * NUMBER_OF_COLUMNS + 300;
Missing visibility keyword

2023-06-09 19:24 UTC, manuelkoso commented on core/src/it/units/sdm/project/game/gui/screens/GameScreen.java
> +    static final int GAME_SCREEN_WORLD_HEIGHT = TILE_SIZE * NUMBER_OF_ROWS + 50;
Missing visibility keyword

2023-06-09 19:32 UTC, manuelkoso commented
Add `protected` instead

2023-06-09 19:41 UTC, peiva-git commented
With`protected` I don't think they're visible ro other classes in the same package

2023-06-10 08:11 UTC, manuelkoso approved these changes

2023-06-10 08:11 UTC, merged