First design (with no tests)
peiva-git/SDM_project pull request #30
Opened 2023-03-14 09:59 UTC by manuelkoso

2023-03-14 10:03 UTC, manuelkoso commented
There are the following TODO:

- [ ] Player method putStone
- [ ] Player method lastMove
- [ ] Player method checkFreedom
- [ ] Board method hasMoreThenOneFreeCell

2023-03-14 10:54 UTC, manuelkoso commented on src/main/java/Game.java
> +    void turn(Player player) {
I forgot the `private` keyword

2023-03-14 11:30 UTC, peiva-git commented on src/main/java/Game.java
> +    private final Player whitePlayer;
Add some annotations on the fields and methods

2023-03-14 11:34 UTC, peiva-git requested changes
Base classes look good, just add annotations on fields and methods where relevant

2023-03-15 09:54 UTC, peiva-git approved these changes
Well done

2023-03-15 09:54 UTC, merged